runtime: python37
entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 5

includes:
  - env-sensitive.yaml

instance_class: B2

manual_scaling:
  instances: 1

# global default cache ttl for all static file handlers
default_expiration: "10m"

handlers:
  - url: /static
    static_dir: static
