runtime: python37
entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 4

includes:
  - env-sensitive.yaml

instance_class: B2

basic_scaling:
  max_instances: 11
  idle_timeout: 10m
